### PR TITLE
fix: typos and translate text hardcoded in TS

### PR DESCRIPTION
**Pull request by mahcr**
Changes:
- Fix typos in Spanish translation
- Translate text hardcoded text in `app.component`

Special thanks to @CharlesElGriego which help me with the spell checking.

### CODE REVIEW

**Comment by mgechev** [comment]
@mahcr there's a conflict. Would you resolve it so we can merge?

**Comment by mahcr** [comment]
For sure

**Comment by mgechev** [comment]
@mahcr any updates?

**Comment by mahcr** [comment]
Updated! Apologies for the late response! @mgechev

**Review by mgechev — APPROVED** [review]

**Comment by mgechev** [comment]
Thanks for your PR!

**Pull request merged**
