### PR TITLE
Open links in new window

### PR DESCRIPTION
**Pull request by theunreal**

### CODE REVIEW

**Comment by StephenFluin** [comment]
I think this only makes sense if all of the links have the same behavior. Can you update and squash the commits?

**Comment by StephenFluin** [comment]
Thanks for the additional links. Can you squash the commits?

**Comment by theunreal** [comment]
Done

**Comment by StephenFluin** [comment]
Sorry, I should have something earlier, but can your remove the package lock as well? The project already has a yarn.lock

**Pull request closed without merging**
