### PR TITLE
fix: minor changes to show updates

### PR DESCRIPTION
**Pull request by santoshyadavdev**

### CODE REVIEW

**Comment by santoshyadav198613** [comment]
Hi @StephenFluin ,
I have moved some changes like forms to medium and Ts version update to basic.

**Comment by StephenFluin** [comment]
Some of these are great, and I disagree with some of these. Mind if I modify this PR or should I make the changes separately?

**Comment by santoshyadav198613** [comment]
> Some of these are great, and I disagree with some of these. Mind if I modify this PR or should I make the changes separately?

Yes sure.

**Comment by santoshyadavdev** [comment]
Hi @StephenFluin,
Should I close this, or are you going to use the same branch for more changes?

**Comment by StephenFluin** [comment]
I just pushed this commit: https://github.com/StephenFluin/angular-update-guide/commit/b591e4d5cf0a57ee024d54973d44e154bd8f3058

**Pull request closed without merging**
